### ISSUE TITLE
Pass initial values to the store

### ISSUE THREAD

**Issue by tokenvolt** [fabiospampinato/overstated#4]
Is there a way to pass initial values of a store instead of defining them in place? I have a requirement where I am not aware of the initial values, since I need to fetch them and only then populate the store.

I'm using `overstated@2.0.0-beta.2` version with `react@16.8.6`

**Comment by fabiospampinato** [comment]
There's no explicit built-in solution for this, but you can implement your own like this:

```ts
class MyStore extends Store {
  constructor ( state ) {
    super ();
    this.state = state;
  }
}
```

And then just pass a pre-instantiated store (since you have to manually instantiate it to pass the actual state to the constructor) to `useStore` or `connect`.

Alternatively you could just pass the fetched state to `this.setState`, perhaps in that scenario you might want to implement a `isLoaded` method in the store.

**Comment by tokenvolt** [comment]
Thanks for the quick response, I've made a PR that makes this feature a built-in, could make a review, please.
