### ISSUE TITLE
How does this compare to react-easy-state

### ISSUE THREAD

**Issue by solidpulse** [fabiospampinato/overstated#7]
I really liked the usage of class as a store!

But react-easy-state has a simpler API without the requirement of  'use' functions and is closer to normal JS.
https://github.com/solkimicreb/react-easy-state

Can we make the API more simpler like the above

**Comment by fabiospampinato** [comment]
I wasn't aware of `react-easy-state` existence, it seems a pretty interesting library. From what I can see from reading the readme some differences might be:

- `react-easy-state`'s "batched" renders sound equivalent to our "suspension" mechanism. But everything is done magically for you in `react-easy-state`, while here you need to call the "autosuspend" method manually. That's because class arrow functions are attached to the class after whatever we put into the constructor function runs, so we can't access them at instantiation time, and the user needs to trigger this manually. I'm not sure we can achieve the same while still using classes as stores and while still supporting class arrow functions. Also maybe their batched rendering system is better than ours, currently we only perform _one_ render after the whole thing is finished, but if that takes a while perhaps you want to refresh the UI multiple times (I'm not sure if that's what's happening in `react-easy-state` or not though). 

- I think `react-easy-state`'s stores can't be instantiated multiple times (at least not without doing anything weird?) because they can't use `this` to reference themselves. This is pretty useful when testing stores and I wouldn't want to renounce to this. On the other end though not using classes ensures that you won't need to call `#bind` on your callbacks, but you also don't need to do that if you define them as class arrow functions, and we could provide a linter rule for this or something.

- Since `react-easy-state`'s stores are pre-instantiated you can't kind of replace them with mocked ones like you can with ours with the help of our "Provider" component. Perhaps that's not super important though.

- `react-easy-state`'s state can be mutated directly (kind of, under the hood Proxies take care of this), this gets rid of a whole class of bugs where someone mutates the state directly but the UI doesn't change because the actual objects comprising the state are actually the same.

- `react-easy-state` tells you to "wrap ALL of your components with view", I'm not sure why that is the case, perhaps the overhead of doing so is minimal and they are trying to minimize the occurrence of the scenario where one forgets to do so and the components don't update properly.

- `react-easy-state` has no equivalent to our "debug" or "Hooks", this will make debuggability worse. But I see no reason why those couldn't be implemented there as well in the future.

- `react-easy-state` has no concept of "composed" stores. I guess explicitly requiring other stores and using them would be a better model, but I'm not sure how JS handles these sorts of cyclic dependencies, I think it may not work at all 🤔 

- `react-easy-state` has no middlewares, and no middlewares on composed stores (which is kind of useful if you need to do something everytime the state anywhere changes, but this could be replaced with a custom event/hook, if you don't use multiple separate composed stores at once).

I haven't actually tried `react-easy-state`, and I'm not exactly sure how it works, but overall its APIs seem quite beautiful, perhaps we could take some inspiration from it for Overstated v3, if there's anything that we can do to make this library easier to use and less error-prone I'm all for it. So far I'm seeing these possible rooms for improvements:

- **Automatic suspension**: perhaps there's a way to do it, like with a custom TS transform that puts the `autosuspend` call at the bottom of the constructor or something.

- **No `Provider` component**: the provider component could easily be removed, at the expense of some testing capabilities, perhaps we could make its usage optional.

- **No `connect` and no `useStore`**: perhaps by using Proxies we could replace explicitly retrieving state/methods with some special wrapper for our components.

- **No `compose`**: perhaps our `compose` function could be replaced with explicitly requiring the other stores, but I'm not sure this is possible.

- **Mutable states**: perhaps via Proxies we can make our states kind-of mutable, so that we can remove the "setState" function entirely.

Perhaps @solkimicreb you might want to join the discussion.

**Comment by fabiospampinato** [comment]
> No compose: perhaps our compose function could be replaced with explicitly requiring the other stores, but I'm not sure this is possible.

Thinking more about this there are some real benefits of having composable stores. For one how would you do something every single time your entire app's state changes in `react-easy-state`? You'd have to subscribe to each store individually I think, with `compose` this gets significantly cleaner.

**Comment by fabiospampinato** [comment]
> No connect and no useStore: perhaps by using Proxies we could replace explicitly retrieving state/methods with some special wrapper for our components.

This has also its downsides, for instance if we want to check if our store has an object like so: `!!MyStore.getFoo ()`, now I think a Proxy-based approach would also re-render the component even when `foo` changes, but we actually don't care about that, we only care about its presence or not.
